# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
# If this option is not defined, the hostname is used.
name: "filebeat"
logging.metrics.enabled: true
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

monitoring:
  enabled: true
  elasticsearch:
    username: elastic
    password: senha

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /src/logs/service1.log
    fields:
      service: service1
    fields_under_root: true

  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /src/logs/service2.log
    fields:
      service: service2
    fields_under_root: true

  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /src/logs/nginx/*
    fields:
      service: nginx
    fields_under_root: true

output.elasticsearch:
  hosts: "http://0.0.0.0:9200"
  username: "elastic"
  password: "senha"
  index: "meus-logs"
setup.kibana:
  host: "http://kibana:5601"

http:
  enabled: true
  host: 0.0.0.0

